### ISSUE TITLE
Move People Search into new tab

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/custom_homepage_bundle#173]
@kreynen commented on [Wed Dec 20 2017](https://github.com/CuBoulder/express/issues/1761)

Move the People search into a tab that will transfer the search query from any other search and does not have any integration with A-Z.

- [ ] https://github.com/CuBoulder/express/issues/1728

<img width="709" alt="screen shot 2017-12-20 at 11 40 14 am" src="https://user-images.githubusercontent.com/385234/34222951-ac381102-e57a-11e7-91cf-a46e61610dd9.png">

<img width="454" alt="screen shot 2017-12-20 at 10 38 26 am" src="https://user-images.githubusercontent.com/385234/34222902-7f9ace96-e57a-11e7-81a7-efbf17fdb924.png">

<img width="708" alt="screen shot 2017-12-20 at 11 40 38 am" src="https://user-images.githubusercontent.com/385234/34222960-b592f06e-e57a-11e7-8ad3-2760825281cc.png">

---

@kevincrafts commented on [Wed Dec 20 2017](https://github.com/CuBoulder/express/issues/1761#issuecomment-353136271)

Should this go in https://github.com/CuBoulder/express_homepage ?

---

@kreynen commented on [Wed Dec 20 2017](https://github.com/CuBoulder/express/issues/1761#issuecomment-353148856)

I can see the case for either including it in what should be custom_homepage or defining just the main search in that bundle and maintaining each search (people/directory/classes/jobs/etc) in their own bundle so they are easier to update when the backends updates.  There are pros and cons to either direction.

---

@kreynen commented on [Mon Aug 20 2018](https://github.com/CuBoulder/express/issues/1761#issuecomment-414404904)

Issue moved to [CuBoulder/custom_homepage_bundle #172](https://github.com/CuBoulder/custom_homepage_bundle/issues/172) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alexfinnarn** [comment]
I'm writing out wht I think this thing is supposed to do and then those musing can be made into smaller issues...

### Search Query

The search query has to work with the current https://www.colorado.edu/search?cse=henry&op=Search if it is to be only tab. The `?cse=` parameter can be used to filter by search term...although, the web search is different than people, and you could make a case for people being able to have different queries in different tabs. In Lil' Shrugger, it was suggested to hold the state of each filter for code and sites. People and Website results could be seen as similar enough to use the same search term between tabs.

### Loading of webpage results

The term "nodes" is used which makes me think of D7 and Express. Is all of the people data supposed to be in the centralized Webcental thingy? If not, then the query is run against an aggregated data store of Express people nodes? If that is the case, then there are two different places to try and fetch data from. Filtering results like in Lil' Shrugger's data table is best done with a complete set of the data.

### Initial page load

If no SSR is used, then you can end up with spinners, timeouts, and bad UX. How is SSR supposed to be done here? I wouldn't suggest loading a Vue app that has to fetch data before displaying. If the user  is on another tab, then the same search result can be fetched in the background, but if you loaded https://www.colorado.edu/people?cse=henry&op=Search, no data would exist yet for the "henry" query.

### Google CSE limitiations 

Does Google CSE use `?cse=` for fetching data no matter what the URI is? So, if the page is loaded with all tabs to end up prefetching data for when a user switches to the "people" tab from the "search" tab how will that impact the CSE analytics? 

If each tab is actually a different page, then the query parameter can be passed via some other key. Any JS code on the "search" tab that interacts with the query parameter can interfere with the "people" search. However, this would require caching the `people/?person=henry` query somewhere on a server for the initial HTML. 

### URI

Is it `/search/people?query-something=henry` or something else? That's what it says in the "Directory/search Scope" Google doc.

### Graph QL?

If the idea is to have "static JSON files" that this embedded app would consume, then doesn't that defeat the puropse of using GraphQL on the front-end. The front-end would be REST in that case. https://akryum.github.io/vue-apollo/guide is a resource for using GraphQL with Vue.

### REST Endpoints

So what will the REST endpoints be then? Just one to grab all the data? How much data is expected to be aggregated across the JSON files?
