### ISSUE TITLE
Update contrib dependencies that are still in use by homepage

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/custom_homepage_bundle#182]
feeds, term_merge, term_reference_tree, views_block_filter_block, views_responsive_grid, postal_code, addressfield and better_exposed_filters

**Comment by jwfuller** [comment]
We got rid of a number of these, so hopefully the list isn't as long

**Comment by jwfuller** [comment]
Looks like BEF is no longer used in the module or in any of the views that I see

**Comment by jwfuller** [comment]
I think the same may be true of `views_block_filter_block` and `views_responsive_grid`.

**Comment by jwfuller** [comment]
`match_redirect` is up to date. `term_merge` has two feature releases including a large rewrite to integrate with the `synonyms` module which we do not use, there are no security fixes in these two versions.

**Comment by kevincrafts** [comment]
I looked through the active views and didn't see anything that would use those extra modules so I think we can safely disable and remove.
